# -*- coding: utf-8 -*-
import re


# List of (regular expression, replacement) pairs for abbreviations in Italian:
abbreviations_it = [
    (re.compile("\\b%s\\." % x[0], re.IGNORECASE), x[1])
    for x in [
        ("Sig", "signore"),
        ("Sig.ra", "signora"),
        ("Sig.na", "signorina"),
        ("Dott", "dottore"),
        ("Dott.ssa", "dottoressa"),
        ("Prof", "professore"),
        ("Prof.ssa", "professoressa"),
        ("Ing", "ingegnere"),
        ("Avv", "avvocato"),
        ("Gen", "generale"),
        ("Col", "colonnello"),
        ("Cap", "capitano"),
        ("Ten", "tenente"),
        ("Serg", "sergente"),
        ("Pres", "presidente"),
        ("Dir", "direttore"),
        ("Amm", "amministratore"),
        ("Rag", "ragioniere"),
        ("Geom", "geometra"),
        ("Arch", "architetto"),
        ("S.p.A", "società per azioni"),
        ("S.r.l", "società a responsabilità limitata"),
        ("S.n.c", "società in nome collettivo"),
        ("S.a.s", "società in accomandita semplice"),
        ("P.A", "pubblica amministrazione"),
        ("P.I", "partita IVA"),
        ("C.F", "codice fiscale"),
        ("N.B", "nota bene"),
        ("P.S", "post scriptum"),
        ("etc", "eccetera"),
        ("ecc", "eccetera"),
        ("ca", "circa"),
        ("max", "massimo"),
        ("min", "minimo"),
        ("tel", "telefono"),
        ("cell", "cellulare"),
        ("fax", "facsimile"),
        ("email", "posta elettronica"),
        ("www", "world wide web"),
        ("http", "hypertext transfer protocol"),
        ("vs", "versus"),
        ("c/o", "presso"),
        ("p.za", "piazza"),
        ("via", "via"),
        ("v.le", "viale"),
        ("c.so", "corso"),
        ("str", "strada"),
        ("loc", "località"),
        ("fraz", "frazione"),
        ("prov", "provincia"),
        ("reg", "regione"),
        ("cap", "codice di avviamento postale"),
        ("km", "chilometri"),
        ("m", "metri"),
        ("cm", "centimetri"),
        ("mm", "millimetri"),
        ("kg", "chilogrammi"),
        ("g", "grammi"),
        ("l", "litri"),
        ("ml", "millilitri"),
        ("h", "ore"),
        ("min", "minuti"),
        ("sec", "secondi"),
        ("°C", "gradi Celsius"),
        ("°F", "gradi Fahrenheit"),
        ("a.C", "avanti Cristo"),
        ("d.C", "dopo Cristo"),
        ("S", "santo"),
        ("S.ta", "santa"),
        ("SS", "santissimo"),
        ("B.to", "beato"),
        ("B.ta", "beata"),
        ("Don", "don"),
        ("Mons", "monsignore"),
        ("Card", "cardinale"),
        ("Papa", "papa"),
        ("Re", "re"),
        ("Regina", "regina"),
        ("Principe", "principe"),
        ("Principessa", "principessa"),
        ("Duca", "duca"),
        ("Duchessa", "duchessa"),
        ("Conte", "conte"),
        ("Contessa", "contessa"),
        ("Barone", "barone"),
        ("Baronessa", "baronessa"),
    ]
] + [
    (re.compile("\\b%s" % x[0]), x[1])
    for x in [
        ("Sig.ra", "signora"),
        ("Sig.na", "signorina"),
        ("Dott.ssa", "dottoressa"),
        ("Prof.ssa", "professoressa"),
    ]
]
